/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PendenteRouteImport } from './routes/pendente'
import { Route as AuthenticatedAtendenteRouteImport } from './routes/_authenticated/atendente'
import { Route as AuthenticatedAuditorRouteImport } from './routes/_authenticated/auditor'
import { Route as AuthenticatedSocioRouteImport } from './routes/_authenticated/socio'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenteRoute = PendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtendenteRoute = AuthenticatedAtendenteRouteImport.update({
  id: '/atendente',
  path: '/atendente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditorRoute = AuthenticatedAuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocioRoute = AuthenticatedSocioRouteImport.update({
  id: '/socio',
  path: '/socio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/atendente': typeof AuthenticatedAtendenteRoute
  '/auditor': typeof AuthenticatedAuditorRoute
  '/socio': typeof AuthenticatedSocioRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/atendente': typeof AuthenticatedAtendenteRoute
  '/auditor': typeof AuthenticatedAuditorRoute
  '/socio': typeof AuthenticatedSocioRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/_authenticated/atendente': typeof AuthenticatedAtendenteRoute
  '/_authenticated/auditor': typeof AuthenticatedAuditorRoute
  '/_authenticated/socio': typeof AuthenticatedSocioRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pendente'
    | '/atendente'
    | '/auditor'
    | '/socio'
    | '/supervisor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pendente'
    | '/atendente'
    | '/auditor'
    | '/socio'
    | '/supervisor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pendente'
    | '/_authenticated/atendente'
    | '/_authenticated/auditor'
    | '/_authenticated/socio'
    | '/_authenticated/supervisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendenteRoute: typeof PendenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendente': {
      id: '/pendente'
      path: '/pendente'
      fullPath: '/pendente'
      preLoaderRoute: typeof PendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atendente': {
      id: '/_authenticated/atendente'
      path: '/atendente'
      fullPath: '/atendente'
      preLoaderRoute: typeof AuthenticatedAtendenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditor': {
      id: '/_authenticated/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuthenticatedAuditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/socio': {
      id: '/_authenticated/socio'
      path: '/socio'
      fullPath: '/socio'
      preLoaderRoute: typeof AuthenticatedSocioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtendenteRoute: typeof AuthenticatedAtendenteRoute
  AuthenticatedAuditorRoute: typeof AuthenticatedAuditorRoute
  AuthenticatedSocioRoute: typeof AuthenticatedSocioRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtendenteRoute: AuthenticatedAtendenteRoute,
  AuthenticatedAuditorRoute: AuthenticatedAuditorRoute,
  AuthenticatedSocioRoute: AuthenticatedSocioRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendenteRoute: PendenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
